export const CultQuestions = [{
        prompt: "1. In what country is it considered a compliment to slurp loudly while eating soup?",
        optionA: "Iceland",
        optionB: "Russia",
        optionC: "Japan",
        optionD: "Colombia",
        answer: "Japan",
        number: "1",
    },
    {
        prompt: "2. You are in Amman, Jordan, and you are invited to go to the souk. Where will you be going?",
        optionA: "Mosque",
        optionB: "Market",
        optionC: "Park",
        optionD: "Turkish bath",
        answer: "Market",
        number: "2",
    },
    {
        prompt: "3. In Italy, mums and roses are the favored flowers to take when invited to dinner. True or False?",
        optionA: "True",
        optionB: "False",
        optionC: "Maybe",
        optionD: "No",
        answer: "False",
        number: "3",
    },
    {
        prompt: "4. In many countries, it is perfectly normal for men to be physically affectionate with each other. True or False?",
        optionA: "True",
        optionB: "False",
        optionC: "Maybet",
        optionD: "No",
        answer: "True",
        number: "4",
    },
    {
        prompt: "5. In which country would showing up half an hour late for an invitation be considered rude?",
        optionA: "Greece",
        optionB: "Switzerland",
        optionC: "Panama",
        optionD: "Guinea",
        answer: "Switzerland",
        number: "5",
    },
    {
        prompt: "6. If you are having dinner with a business partner in Argentina, when is it appropriate to talk business?",
        optionA: "As soon as you sit down at the table",
        optionB: "After some polite table conversation",
        optionC: "After the meal is through",
        optionD: "Never",
        answer: "After some polite table conversation",
        number: "6",
    },
    {
        prompt: "7. In Egypt, you have been invited to a meal at a family home. Towards the end of the meal you are very full. Your hostess offers you more food. What should you do?",
        optionA: "Politely refuse.",
        optionB: "Accept and eat everything on your plate.",
        optionC: "Accept and take a small bite.",
        optionD: "Accept and ask if you can take it with you.",
        answer: "Accept and take a small bite.",
        number: "7",
    },
    {
        prompt: "8. While in South Korea for a business meeting, you present a gift to a business associate to thank him for his hospitality and to build the relationship. He refuses to accept the gift. You should:",
        optionA: "Apologize for offending him",
        optionB: "Insist he takes the gift until it is accepted",
        optionC: "Quietly keep the gift",
        optionD: "do nothing",
        answer: "Insist he takes the gift until it is accepted",
        number: "8",
    },
    {
        prompt: "9. In India, you are invited to a friend’s house to share a meal of rice and curry. What is the best way to eat?",
        optionA: "Using a spoon",
        optionB: "Using your left hand only",
        optionC: "Using your right hand only",
        optionD: "None of These",
        answer: "Using your right hand only",
        number: "9",
    },
    {
        prompt: "10.What is the name for a computer pointing device?",
        optionA: "Brazil",
        optionB: "Uganda",
        optionC: "Thailand",
        optionD: "Germany",
        answer: "Germany",
        number: "10",
    },
]